### ISSUE TITLE
Readme Links Aren't rendering properly

### ISSUE THREAD

**Issue by eschapp** [Revolutionz-TIY/CrossoverProject#1]
ie https://github.com/Revolutionz-TIY/CrossoverProject/blob/master/www.github.com/billgottsch is the destination rather than www.github.com/billgottsch. This results in a 404 error.

**Comment by jenessawhite** [comment]
Thanks Eric! The links are currently set up properly, so we'll have to look into why the URL is being added to the current address bar.

**Comment by eschapp** [comment]
Yeah your markdown looks solid. I'd maybe try making them absolute paths to see if that helps.

**Comment by jenessawhite** [comment]
Perfect. thanks Eric!
